ALTER TABLE projects
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE tasks
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE users
    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;


